#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	# Create user and group for glance
	if ! getent group glance > /dev/null 2>&1 ; then
		addgroup --quiet --system glance >/dev/null
	fi
	if ! getent passwd glance > /dev/null 2>&1 ; then
		adduser --quiet --system --home /var/lib/glance --ingroup glance --no-create-home --shell /bin/false glance
	fi
	chown glance:glance /var/lib/glance -R
fi

#DEBHELPER#
