#!/bin/sh

set -e

case $1 in
    purge)
	echo "Purging glance. Backup of /var/lib/glance can be found at /var/lib/glance.tar.bz2"
	if ( getent passwd glance) > /dev/null 2>&1; then
	    userdel glance || true
	fi

	if ( getent group glance) > /dev/null 2>&1; then
	    groupdel glance || true
	fi

	[ -e /var/lib/glance ] && rm -rf /var/lib/glance
	[ -e /var/log/glance ] && rm -rf /var/log/glance
	;;
esac

#DEBHELPER#
